class Hero
  HEROES = [
    { id: 1, name: "npc_dota_hero_antimage", en_name: "Anti-Mage", cn_name: "敌法师" },
    { id: 2, name: "npc_dota_hero_axe", en_name: "Axe", cn_name: "斧王" },
    { id: 3, name: "npc_dota_hero_bane", en_name: "Bane", cn_name: "祸乱之源" },
    { id: 4, name: "npc_dota_hero_bloodseeker", en_name: "Bloodseeker", cn_name: "血魔" },
    { id: 5, name: "npc_dota_hero_crystal_maiden", en_name: "Crystal Maiden", cn_name: "水晶室女" },
    { id: 6, name: "npc_dota_hero_drow_ranger", en_name: "Drow Ranger", cn_name: "卓尔游侠" },
    { id: 7, name: "npc_dota_hero_earthshaker", en_name: "Earthshaker", cn_name: "撼地者" },
    { id: 8, name: "npc_dota_hero_juggernaut", en_name: "Juggernaut", cn_name: "主宰" },
    { id: 9, name: "npc_dota_hero_mirana", en_name: "Mirana", cn_name: "米拉娜" },
    { id: 10, name: "npc_dota_hero_morphling", en_name: "Morphling", cn_name: "变体精灵" },
    { id: 11, name: "npc_dota_hero_nevermore", en_name: "Shadow Fiend", cn_name: "影魔" },
    { id: 12, name: "npc_dota_hero_phantom_lancer", en_name: "Phantom Lancer", cn_name: "幻影长矛手" },
    { id: 13, name: "npc_dota_hero_puck", en_name: "Puck", cn_name: "帕克" },
    { id: 14, name: "npc_dota_hero_pudge", en_name: "Pudge", cn_name: "帕吉" },
    { id: 15, name: "npc_dota_hero_razor", en_name: "Razor", cn_name: "剃刀" },
    { id: 16, name: "npc_dota_hero_sand_king", en_name: "Sand King", cn_name: "沙王" },
    { id: 17, name: "npc_dota_hero_storm_spirit", en_name: "Storm Spirit", cn_name: "风暴之灵" },
    { id: 18, name: "npc_dota_hero_sven", en_name: "Sven", cn_name: "斯温" },
    { id: 19, name: "npc_dota_hero_tiny", en_name: "Tiny", cn_name: "小小" },
    { id: 20, name: "npc_dota_hero_vengefulspirit", en_name: "Vengeful Spirit", cn_name: "复仇之魂" },
    { id: 21, name: "npc_dota_hero_windrunner", en_name: "Windranger", cn_name: "风行者" },
    { id: 22, name: "npc_dota_hero_zuus", en_name: "Zeus", cn_name: "宙斯" },
    { id: 23, name: "npc_dota_hero_kunkka", en_name: "Kunkka", cn_name: "昆卡" },
    { id: 25, name: "npc_dota_hero_lina", en_name: "Lina", cn_name: "莉娜" },
    { id: 26, name: "npc_dota_hero_lion", en_name: "Lion", cn_name: "莱恩" },
    { id: 27, name: "npc_dota_hero_shadow_shaman", en_name: "Shadow Shaman", cn_name: "暗影萨满" },
    { id: 28, name: "npc_dota_hero_slardar", en_name: "Slardar", cn_name: "斯拉达" },
    { id: 29, name: "npc_dota_hero_tidehunter", en_name: "Tidehunter", cn_name: "潮汐猎人" },
    { id: 30, name: "npc_dota_hero_witch_doctor", en_name: "Witch Doctor", cn_name: "巫医" },
    { id: 31, name: "npc_dota_hero_lich", en_name: "Lich", cn_name: "巫妖" },
    { id: 32, name: "npc_dota_hero_riki", en_name: "Riki", cn_name: "力丸" },
    { id: 33, name: "npc_dota_hero_enigma", en_name: "Enigma", cn_name: "谜团" },
    { id: 34, name: "npc_dota_hero_tinker", en_name: "Tinker", cn_name: "修补匠" },
    { id: 35, name: "npc_dota_hero_sniper", en_name: "Sniper", cn_name: "狙击手" },
    { id: 36, name: "npc_dota_hero_necrolyte", en_name: "Necrophos", cn_name: "瘟疫法师" },
    { id: 37, name: "npc_dota_hero_warlock", en_name: "Warlock", cn_name: "术士" },
    { id: 38, name: "npc_dota_hero_beastmaster", en_name: "Beastmaster", cn_name: "兽王" },
    { id: 39, name: "npc_dota_hero_queenofpain", en_name: "Queen of Pain", cn_name: "痛苦女王" },
    { id: 40, name: "npc_dota_hero_venomancer", en_name: "Venomancer", cn_name: "剧毒术士" },
    { id: 41, name: "npc_dota_hero_faceless_void", en_name: "Faceless Void", cn_name: "虚空假面" },
    { id: 42, name: "npc_dota_hero_skeleton_king", en_name: "Wraith King", cn_name: "冥魂大帝" },
    { id: 43, name: "npc_dota_hero_death_prophet", en_name: "Death Prophet", cn_name: "死亡先知" },
    { id: 44, name: "npc_dota_hero_phantom_assassin", en_name: "Phantom Assassin", cn_name: "幻影刺客" },
    { id: 45, name: "npc_dota_hero_pugna", en_name: "Pugna", cn_name: "帕格纳" },
    { id: 46, name: "npc_dota_hero_templar_assassin", en_name: "Templar Assassin", cn_name: "圣堂刺客" },
    { id: 47, name: "npc_dota_hero_viper", en_name: "Viper", cn_name: "冥界亚龙" },
    { id: 48, name: "npc_dota_hero_luna", en_name: "Luna", cn_name: "露娜" },
    { id: 49, name: "npc_dota_hero_dragon_knight", en_name: "Dragon Knight", cn_name: "龙骑士" },
    { id: 50, name: "npc_dota_hero_dazzle", en_name: "Dazzle", cn_name: "戴泽" },
    { id: 51, name: "npc_dota_hero_rattletrap", en_name: "Clockwerk", cn_name: "发条技师" },
    { id: 52, name: "npc_dota_hero_leshrac", en_name: "Leshrac", cn_name: "拉席克" },
    { id: 53, name: "npc_dota_hero_furion", en_name: "Nature's Prophet", cn_name: "先知" },
    { id: 54, name: "npc_dota_hero_life_stealer", en_name: "Lifestealer", cn_name: "噬魂鬼" },
    { id: 55, name: "npc_dota_hero_dark_seer", en_name: "Dark Seer", cn_name: "黑暗贤者" },
    { id: 56, name: "npc_dota_hero_clinkz", en_name: "Clinkz", cn_name: "克林克兹" },
    { id: 57, name: "npc_dota_hero_omniknight", en_name: "Omniknight", cn_name: "全能骑士" },
    { id: 58, name: "npc_dota_hero_enchantress", en_name: "Enchantress", cn_name: "魅惑魔女" },
    { id: 59, name: "npc_dota_hero_huskar", en_name: "Huskar", cn_name: "哈斯卡" },
    { id: 60, name: "npc_dota_hero_night_stalker", en_name: "Night Stalker", cn_name: "暗夜魔王" },
    { id: 61, name: "npc_dota_hero_broodmother", en_name: "Broodmother", cn_name: "育母蜘蛛" },
    { id: 62, name: "npc_dota_hero_bounty_hunter", en_name: "Bounty Hunter", cn_name: "赏金猎人" },
    { id: 63, name: "npc_dota_hero_weaver", en_name: "Weaver", cn_name: "编织者" },
    { id: 64, name: "npc_dota_hero_jakiro", en_name: "Jakiro", cn_name: "杰奇洛" },
    { id: 65, name: "npc_dota_hero_batrider", en_name: "Batrider", cn_name: "蝙蝠骑士" },
    { id: 66, name: "npc_dota_hero_chen", en_name: "Chen", cn_name: "陈" },
    { id: 67, name: "npc_dota_hero_spectre", en_name: "Spectre", cn_name: "幽鬼" },
    { id: 68, name: "npc_dota_hero_ancient_apparition", en_name: "Ancient Apparition", cn_name: "远古冰魄" },
    { id: 69, name: "npc_dota_hero_doom_bringer", en_name: "Doom", cn_name: "末日使者" },
    { id: 70, name: "npc_dota_hero_ursa", en_name: "Ursa", cn_name: "熊战士" },
    { id: 71, name: "npc_dota_hero_spirit_breaker", en_name: "Spirit Breaker", cn_name: "裂魂人" },
    { id: 72, name: "npc_dota_hero_gyrocopter", en_name: "Gyrocopter", cn_name: "矮人直升机" },
    { id: 73, name: "npc_dota_hero_alchemist", en_name: "Alchemist", cn_name: "炼金术士" },
    { id: 74, name: "npc_dota_hero_invoker", en_name: "Invoker", cn_name: "祈求者" },
    { id: 75, name: "npc_dota_hero_silencer", en_name: "Silencer", cn_name: "沉默术士" },
    { id: 76, name: "npc_dota_hero_obsidian_destroyer", en_name: "Outworld Destroyer", cn_name: "殁境神蚀者" },
    { id: 77, name: "npc_dota_hero_lycan", en_name: "Lycan", cn_name: "狼人" },
    { id: 78, name: "npc_dota_hero_brewmaster", en_name: "Brewmaster", cn_name: "酒仙" },
    { id: 79, name: "npc_dota_hero_shadow_demon", en_name: "Shadow Demon", cn_name: "暗影恶魔" },
    { id: 80, name: "npc_dota_hero_lone_druid", en_name: "Lone Druid", cn_name: "德鲁伊" },
    { id: 81, name: "npc_dota_hero_chaos_knight", en_name: "Chaos Knight", cn_name: "混沌骑士" },
    { id: 82, name: "npc_dota_hero_meepo", en_name: "Meepo", cn_name: "米波" },
    { id: 83, name: "npc_dota_hero_treant", en_name: "Treant Protector", cn_name: "树精卫士" },
    { id: 84, name: "npc_dota_hero_ogre_magi", en_name: "Ogre Magi", cn_name: "食人魔魔法师" },
    { id: 85, name: "npc_dota_hero_undying", en_name: "Undying", cn_name: "不朽尸王" },
    { id: 86, name: "npc_dota_hero_rubick", en_name: "Rubick", cn_name: "拉比克" },
    { id: 87, name: "npc_dota_hero_disruptor", en_name: "Disruptor", cn_name: "干扰者" },
    { id: 88, name: "npc_dota_hero_nyx_assassin", en_name: "Nyx Assassin", cn_name: "司夜刺客" },
    { id: 89, name: "npc_dota_hero_naga_siren", en_name: "Naga Siren", cn_name: "娜迦海妖" },
    { id: 90, name: "npc_dota_hero_keeper_of_the_light", en_name: "Keeper of the Light", cn_name: "光之守卫" },
    { id: 91, name: "npc_dota_hero_wisp", en_name: "Io", cn_name: "艾欧" },
    { id: 92, name: "npc_dota_hero_visage", en_name: "Visage", cn_name: "维萨吉" },
    { id: 93, name: "npc_dota_hero_slark", en_name: "Slark", cn_name: "斯拉克" },
    { id: 94, name: "npc_dota_hero_medusa", en_name: "Medusa", cn_name: "美杜莎" },
    { id: 95, name: "npc_dota_hero_troll_warlord", en_name: "Troll Warlord", cn_name: "巨魔战将" },
    { id: 96, name: "npc_dota_hero_centaur", en_name: "Centaur Warrunner", cn_name: "半人马战行者" },
    { id: 97, name: "npc_dota_hero_magnataur", en_name: "Magnus", cn_name: "马格纳斯" },
    { id: 98, name: "npc_dota_hero_shredder", en_name: "Timbersaw", cn_name: "伐木机" },
    { id: 99, name: "npc_dota_hero_bristleback", en_name: "Bristleback", cn_name: "钢背兽" },
    { id: 100, name: "npc_dota_hero_tusk", en_name: "Tusk", cn_name: "巨牙海民" },
    { id: 101, name: "npc_dota_hero_skywrath_mage", en_name: "Skywrath Mage", cn_name: "天怒法师" },
    { id: 102, name: "npc_dota_hero_abaddon", en_name: "Abaddon", cn_name: "亚巴顿" },
    { id: 103, name: "npc_dota_hero_elder_titan", en_name: "Elder Titan", cn_name: "上古巨神" },
    { id: 104, name: "npc_dota_hero_legion_commander", en_name: "Legion Commander", cn_name: "军团指挥官" },
    { id: 105, name: "npc_dota_hero_techies", en_name: "Techies", cn_name: "工程师" },
    { id: 106, name: "npc_dota_hero_ember_spirit", en_name: "Ember Spirit", cn_name: "灰烬之灵" },
    { id: 107, name: "npc_dota_hero_earth_spirit", en_name: "Earth Spirit", cn_name: "大地之灵" },
    { id: 108, name: "npc_dota_hero_abyssal_underlord", en_name: "Underlord", cn_name: "孽主" },
    { id: 109, name: "npc_dota_hero_terrorblade", en_name: "Terrorblade", cn_name: "恐怖利刃" },
    { id: 110, name: "npc_dota_hero_phoenix", en_name: "Phoenix", cn_name: "凤凰" },
    { id: 111, name: "npc_dota_hero_oracle", en_name: "Oracle", cn_name: "神谕者" },
    { id: 112, name: "npc_dota_hero_winter_wyvern", en_name: "Winter Wyvern", cn_name: "寒冬飞龙" },
    { id: 113, name: "npc_dota_hero_arc_warden", en_name: "Arc Warden", cn_name: "天穹守望者" },
    { id: 114, name: "npc_dota_hero_monkey_king", en_name: "Monkey King", cn_name: "齐天大圣" },
    { id: 119, name: "npc_dota_hero_dark_willow", en_name: "Dark Willow", cn_name: "邪影芳灵" },
    { id: 120, name: "npc_dota_hero_pangolier", en_name: "Pangolier", cn_name: "石鳞剑士" },
    { id: 121, name: "npc_dota_hero_grimstroke", en_name: "Grimstroke", cn_name: "天涯墨客" },
    { id: 123, name: "npc_dota_hero_hoodwink", en_name: "Hoodwink", cn_name: "森海飞霞" },
    { id: 126, name: "npc_dota_hero_void_spirit", en_name: "Void Spirit", cn_name: "虚无之灵" },
    { id: 128, name: "npc_dota_hero_snapfire", en_name: "Snapfire", cn_name: "电炎绝手" },
    { id: 129, name: "npc_dota_hero_mars", en_name: "Mars", cn_name: "玛尔斯" },
    { id: 131, name: "npc_dota_hero_ringmaster", en_name: "Ringmaster", cn_name: "百戏大王" },
    { id: 135, name: "npc_dota_hero_dawnbreaker", en_name: "Dawnbreaker", cn_name: "破晓辰星" },
    { id: 136, name: "npc_dota_hero_marci", en_name: "Marci", cn_name: "玛西" },
    { id: 137, name: "npc_dota_hero_primal_beast", en_name: "Primal Beast", cn_name: "獸" },
    { id: 138, name: "npc_dota_hero_muerta", en_name: "Muerta", cn_name: "琼英碧灵" },
    { id: 145, name: "npc_dota_hero_kez", en_name: "Kez", cn_name: "凯" },
    { id: 155, name: "npc_dota_hero_largo", en_name: "Largo", cn_name: "拉戈" }
  ]

  class << self
    def find_by_id(id)
      new(id)
    end

    def find_by_name(name)
      @heroes_by_name ||= {}
      @heroes_by_name[name] ||= begin
        hero_data = HEROES.find { |hero| hero[:name] == name }
        new(hero_data.fetch(:id))
      end
    end
  end

  attr_reader :id, :name, :en_name, :cn_name

  def initialize(id)
    @id = id.to_i
    hero_data = HEROES.find { |hero| hero[:id] == id }
    @name = hero_data.fetch(:name)
    @en_name = hero_data.fetch(:en_name)
    @cn_name = hero_data.fetch(:cn_name)
  end
end
